# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/
#            security: false

        page1:
            pattern: ^/page/1
#            http_basic: ~
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
#                always_use_default_target_path: true
#                default_target_path: page1
#            remember_me:
#                secret:   '%secret%'
#                lifetime: 300
#                path:     /
#                domain:   ~

            provider: our_db_provider

            logout:
                path: /logout
                target: /
        page2:
            anonymous: ~
            pattern: ^/page/2
            form_login:
                login_path: login
                check_path: login
                default_target_path: page2
#            remember_me:
#                secret:   '%secret%'
#                lifetime: 300
#                path:     /
#                domain:   ~

            provider: our_db_provider
            logout:
                path: /logout
                target: /
        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            provider: our_db_provider
#            remember_me:
#                secret:   '%secret%'
#                lifetime: 300
#                path:     /
#                domain:   ~
            logout:
                path: /logout
                target: /

    encoders:
        AppBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/page/1, roles: ROLE_ADMIN }
#        - { path: ^/page/1, allow_if: "has_role('ROLE_ADMIN')" }
#        - { path: ^/user/*, allow_if: "has_role('ADMIN')" }